### ISSUE TITLE
Exclude packages

### ISSUE THREAD

**Issue by thiagolinhares** [EncoreTechnologies/puppet-patching#64]
Hi there.
It would be nice to have an option to exclude certain packages from updating/upgrading.

```
groups:
  - name: xpto_special_package
    vars:
      **excluded_packages: mysql-server, apache**
    targets:
      - abc123.domain.tld
      - def4556.domain.tld

```

As to identify which package is the right for that O.S, we could use spec class such as Puppet does.
E.g: https://github.com/puppetlabs/puppetlabs-apache/blob/master/spec/classes/apache_spec.rb
